# Generated by Django 3.1.2 on 2020-12-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
