# Generated by Django 3.1.2 on 2020-11-09 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("examresults", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsersInterestedCivilServiceTitle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_number", models.CharField(max_length=200)),
                (
                    "civil_service_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examresults.civilservicestitle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("exam_number", "user")},
            },
        ),
        migrations.CreateModel(
            name="UsersCurrentCivilServiceTitle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "civil_service_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examresults.civilservicestitle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("civil_service_title", "user")},
            },
        ),
    ]
