# Generated by Django 3.1.2 on 2020-11-10 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("examresults", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("signin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsersCivilServiceTitle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_interested",
                    models.BooleanField(default=False, verbose_name="is_interested"),
                ),
                (
                    "civil_service_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examresults.civilservicestitle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("civil_service_title", "user")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="usersinterestedcivilservicetitle",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="usersinterestedcivilservicetitle",
            name="civil_service_title",
        ),
        migrations.RemoveField(
            model_name="usersinterestedcivilservicetitle",
            name="user",
        ),
        migrations.DeleteModel(
            name="UsersCurrentCivilServiceTitle",
        ),
        migrations.DeleteModel(
            name="UsersInterestedCivilServiceTitle",
        ),
    ]
