# Generated by Django 3.1.2 on 2020-11-15 17:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("examresults", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_notified",
                    models.BooleanField(default=False, verbose_name="is_notified"),
                ),
                (
                    "civil_service_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examresults.civilservicestitle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("civil_service_title", "user")},
            },
        ),
        migrations.CreateModel(
            name="ExamResultsSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(999999),
                            django.core.validators.MinValueValidator(1000),
                        ]
                    ),
                ),
                (
                    "is_notified",
                    models.BooleanField(default=False, verbose_name="is_notified"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("exam_number", "user")},
            },
        ),
    ]
