# Generated by Django 3.1.2 on 2020-12-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUsModel",
            fields=[
                ("contact_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=32, null=True)),
                ("email", models.CharField(blank=True, max_length=64, null=True)),
                ("subject", models.CharField(blank=True, max_length=256, null=True)),
                ("message", models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                "verbose_name_plural": "Contact Us",
            },
        ),
    ]
