# Generated by Django 3.1.2 on 2020-11-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examresults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresultsactive',
            name='display_exam_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
