# Generated by Django 3.1.2 on 2020-10-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examresults', '0002_auto_20201018_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresultsactive',
            options={'verbose_name_plural': 'Exam Results(Active)'},
        ),
        migrations.AlterModelOptions(
            name='examresultsterminated',
            options={'verbose_name_plural': 'Exam Results(Terminated)'},
        ),
    ]
